spring:
  cloud:
    consul:
      host: ${DISCOVERY_SERVICE_URL}
      port: ${DISCOVERY_PORT}
      discovery:
        prefer-ip-address: true
    gateway:
      discovery:
        locator:
          enabled: true
server:
  port: ${PORT:8080}


